version: "3.7"
services:
  app:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "30"
        max-size: "10m"
    ulimits:
      nproc: 65535
      nofile:
        soft: 30000
        hard: 40000
    user: '${UID:-1000}:${GID:-1000}'
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    command: [ "./rr","serve" ]
    ports:
      - 18080:8080
    volumes:
      - ./app:/var/www/app
