rpc:
  listen: tcp://:6001
server:
  command: "php psr-worker.php"
logs:
  mode: development
  level: debug
  encoding: console
  output: stderr
  err_output: stderr
  channels:
    http:
      mode: development
      level: debug
      encoding: console
      output: stdout
      err_output: stderr
    server:
      mode: development
      level: debug
      encoding: console
      output: stdout
      err_output: stdout

http:
  address: 0.0.0.0:8080
  max_request_size: 32
  access_logs: true
  middleware: [ "headers" ]
  trusted_subnets: [
      "10.0.0.0/8",
      "127.0.0.0/8",
      "172.16.0.0/12",
      "172.10.10.0/24",
      "192.168.0.0/16",
      "::1/128",
      "fc00::/7",
      "fe80::/10",
  ]
  uploads:
    dir: "/tmp"
    forbid: [ ".php", ".exe", ".bat", ".sh" ]
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
    response:
      X-Powered-By: "RoadRunner"
  pool:
    debug: false
    num_workers: 1000
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 0s
      max_worker_memory: 64
